Write-Host "---=== Help ===---"

Write-Host ".\command_help.ps1          - Shows this help"
Write-Host ".\command_compile.ps1       - Compiles the project"
Write-Host ".\command_build.ps1         - Builds the project"
Write-Host ".\command_fix.ps1           - Runs dart analyze and dart fix"
Write-Host ".\command_docker_build.ps1  - Builds the docker image locally"
Write-Host ".\command_docker_run.ps1    - Runs docker locally"
Write-Host ".\command_docker_upload.ps1 - Upload a new version of docker image (requires version parameter)"
Write-Host ".\command_k8s.ps1           - Create local Kubernetes deployments with kind"
