
apiVersion: v1
kind: Namespace
metadata:
  name: todos-web-ns
  labels:
    name: todos-web-ns
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todos-web-deployment
  namespace: todos-web-ns
spec:
  selector:
    matchLabels:
      app: todos-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todos-web-app
    spec:
      containers:
      - name: todos-web-app
        image: flutter-todos-web:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todos-web-service
  namespace: todos-web-ns
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: todos-web-app
---
apiVersion: v1
kind: Service
metadata:
  name: todos-web-port-forwarding
spec:
  selector:
    app: todos-app
  ports:
    - name: todos-web-http
      protocol: TCP
      port: 8080
      targetPort: 8081
  type: NodePort